#!/usr/bin/env bash
set -euo pipefail

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "Run this script as root or with sudo."
    exit 1
  fi
}

valid_ipv4() {
  local ip="$1"
  local IFS=.
  local -a o
  read -r -a o <<< "$ip"
  [[ ${#o[@]} -eq 4 ]] || return 1
  for x in "${o[@]}"; do
    [[ "$x" =~ ^[0-9]+$ ]] || return 1
    (( x >= 0 && x <= 255 )) || return 1
  done
}

choose_timezone() {
  local query choice
  local -a zones=()

  while true; do
    echo
    read -rp "Enter a timezone search term (e.g. Europe, Asia, Berlin): " query
    mapfile -t zones < <(timedatectl list-timezones | grep -i -- "${query:-.}" || true)

    if ((${#zones[@]} == 0)); then
      echo "No matching timezones found."
      continue
    fi

    echo
    select choice in "${zones[@]}"; do
      if [[ -n "${choice:-}" ]]; then
        timedatectl set-timezone "$choice"
        echo "Timezone set to: $choice"
        return 0
      fi
      echo "Invalid choice."
    done
  done
}

install_chrony() {
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y chrony
  systemctl disable --now systemd-timesyncd 2>/dev/null || true
}

configure_client() {
  local server_ip="$1"
  local conf="/etc/chrony/chrony.conf"
  local backup="${conf}.bak.$(date +%F_%H%M%S)"

  cp "$conf" "$backup"

  cat > "$conf" <<EOF
# Generated by setup-ntp-client.sh
# NTP server:
server $server_ip iburst prefer

driftfile /var/lib/chrony/chrony.drift
rtcsync
makestep 1.0 3
EOF
}

start_chrony() {
  systemctl daemon-reload
  systemctl enable chrony
  systemctl restart chrony

  if ! systemctl is-active --quiet chrony; then
    echo "chrony failed to start."
    systemctl status chrony --no-pager
    exit 1
  fi
}

main() {
  require_root

  install_chrony
  choose_timezone

  echo
  while true; do
    read -rp "Enter NTP server IP address: " SERVER_IP
    if valid_ipv4 "$SERVER_IP"; then
      break
    fi
    echo "Invalid IPv4 address."
  done

  configure_client "$SERVER_IP"
  start_chrony

  sleep 2
  chronyc -a makestep 2>/dev/null || true

  echo
  echo "Client configured."
  echo "Timezone: $(timedatectl show -p Timezone --value)"
  echo "NTP server: $SERVER_IP"
  echo
  chronyc tracking || true
  echo
  chronyc sources -v || true
  echo
  date
}

main "$@"