#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <ntp-server-ip>"
  exit 1
fi

SERVER_IP="$1"

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "Run this script as root or with sudo."
    exit 1
  fi
}

valid_ipv4() {
  local ip="$1"
  local IFS=.
  local -a o
  read -r -a o <<< "$ip"
  [[ ${#o[@]} -eq 4 ]] || return 1
  for x in "${o[@]}"; do
    [[ "$x" =~ ^[0-9]+$ ]] || return 1
    (( x >= 0 && x <= 255 )) || return 1
  done
}

install_chrony() {
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y chrony
  systemctl disable --now systemd-timesyncd 2>/dev/null || true
}

configure_timezone() {
  timedatectl set-timezone Asia/Tehran
}

configure_chrony() {
  local conf="/etc/chrony/chrony.conf"
  cp "$conf" "${conf}.bak.$(date +%F_%H%M%S)"

  cat > "$conf" <<EOF
# Generated by ntp-client-non-interactive.sh
server $SERVER_IP iburst prefer

driftfile /var/lib/chrony/chrony.drift
rtcsync
makestep 1.0 3
EOF
}

start_chrony() {
  systemctl daemon-reload
  systemctl enable chrony
  systemctl restart chrony

  if ! systemctl is-active --quiet chrony; then
    echo "chrony failed to start."
    systemctl status chrony --no-pager
    exit 1
  fi
}

force_step_sync() {
  sleep 2
  chronyc -a makestep 2>/dev/null || true
}

show_status() {
  echo
  echo "=== CLIENT STATUS ==="
  timedatectl status
  echo
  chronyc tracking || true
  echo
  chronyc sources -v || true
  echo
  date
}

main() {
  require_root
  valid_ipv4 "$SERVER_IP" || { echo "Invalid IPv4 address: $SERVER_IP"; exit 1; }
  install_chrony
  configure_timezone
  configure_chrony
  start_chrony
  force_step_sync
  show_status
}

main "$@"