#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 'YYYY-MM-DD HH:MM:SS'"
  exit 1
fi

NEW_TIME="$1"

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "Run this script as root or with sudo."
    exit 1
  fi
}

validate_time_format() {
  if [[ ! "$NEW_TIME" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
    echo "Invalid time format. Use: YYYY-MM-DD HH:MM:SS"
    exit 1
  fi
}

install_chrony() {
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y chrony
  systemctl disable --now systemd-timesyncd 2>/dev/null || true
}

configure_timezone() {
  timedatectl set-timezone Asia/Tehran
}

set_manual_time() {
  timedatectl set-ntp false
  timedatectl set-time "$NEW_TIME"
}

configure_chrony() {
  local conf="/etc/chrony/chrony.conf"
  cp "$conf" "${conf}.bak.$(date +%F_%H%M%S)"

  cat > "$conf" <<'EOF'
# Generated by ntp-server-non-interactive.sh
# Manual-only NTP server

driftfile /var/lib/chrony/chrony.drift
rtcsync
makestep 1.0 3

# Allow all clients
allow
local stratum 10
EOF
}

start_chrony() {
  systemctl daemon-reload
  systemctl enable chrony
  systemctl restart chrony

  if ! systemctl is-active --quiet chrony; then
    echo "chrony failed to start."
    systemctl status chrony --no-pager
    exit 1
  fi
}

open_firewall() {
  if command -v ufw >/dev/null 2>&1; then
    ufw allow 123/udp >/dev/null 2>&1 || true
  fi
}

show_status() {
  echo
  echo "=== SERVER STATUS ==="
  timedatectl status
  echo
  chronyc tracking || true
  echo
  chronyc sources -v || true
  echo
  date
}

main() {
  require_root
  validate_time_format
  install_chrony
  configure_timezone
  set_manual_time
  configure_chrony
  open_firewall
  start_chrony
  show_status
}

main "$@"