#!/usr/bin/env bash
# ntp-server-setup-multi.sh
# Cross-distro, non-interactive chrony NTP *server* setup with a --dry-run mode.
#
# Supports:
#   - Debian / Ubuntu        (apt-get, service "chrony",  config /etc/chrony/chrony.conf, ufw)
#   - RHEL / CentOS / Fedora / Rocky / Alma
#                            (dnf or yum, service "chronyd", config /etc/chrony.conf, firewalld)
#
# The distribution family, package manager, service name, config path and
# firewall tool are all auto-detected. Pass --dry-run to print the chrony.conf
# that WOULD be written (and the actions that would run) without touching the
# system, installing anything, or starting any service.
#
# Usage:
#   ntp-server-setup-multi.sh [options]
#
# Options:
#   -m, --mode MODE       "online" (sync from a pool + local fallback) or
#                         "manual" (offline authoritative, stratum 10).
#                         Default: online.
#   -t, --time "T"        Manual time "YYYY-MM-DD HH:MM:SS" (required for manual mode).
#   -p, --pool POOL       NTP pool/hostname for online mode. Default: pool.ntp.org.
#   -a, --allow CIDR      Client subnet allowed to query (default 0.0.0.0/0).
#   -z, --timezone ZONE   Timezone to set, e.g. Europe/Berlin (default: leave as-is).
#   -n, --dry-run         Print the config and planned actions; change nothing.
#   -h, --help            Show this help.
#
# Exit codes:
#   0  success (or dry-run completed)
#   1  an action failed / unsupported distro
#   2  bad arguments
#   3  not run as root (only enforced when NOT a dry-run)
set -euo pipefail

MODE="online"
MANUAL_TIME=""
POOL="pool.ntp.org"
ALLOW="0.0.0.0/0"
TIMEZONE=""
DRY_RUN="no"

usage() {
  grep '^#' "$0" | sed 's/^# \{0,1\}//' | sed '1d'
}

# ---- argument parsing ----
while [[ $# -gt 0 ]]; do
  case "$1" in
    -m|--mode) MODE="${2:-}"; shift ;;
    -t|--time) MANUAL_TIME="${2:-}"; shift ;;
    -p|--pool) POOL="${2:-}"; shift ;;
    -a|--allow) ALLOW="${2:-}"; shift ;;
    -z|--timezone) TIMEZONE="${2:-}"; shift ;;
    -n|--dry-run) DRY_RUN="yes" ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; echo "Try --help." >&2; exit 2 ;;
  esac
  shift
done

if [[ "$MODE" != "online" && "$MODE" != "manual" ]]; then
  echo "Invalid mode: $MODE (expected 'online' or 'manual')." >&2
  exit 2
fi

if [[ "$MODE" == "manual" ]]; then
  if [[ -z "$MANUAL_TIME" ]]; then
    echo "Manual mode requires --time 'YYYY-MM-DD HH:MM:SS'." >&2
    exit 2
  fi
  if [[ ! "$MANUAL_TIME" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
    echo "Invalid time format: '$MANUAL_TIME'. Use: YYYY-MM-DD HH:MM:SS" >&2
    exit 2
  fi
fi

# ---- distro detection ----
# Sets: DISTRO_FAMILY, PKG_MGR, PKG_INSTALL, SERVICE, CONF, FIREWALL
detect_distro() {
  local id="" like=""
  if [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    id="${ID:-}"
    like="${ID_LIKE:-}"
  fi

  if [[ "$id" =~ (debian|ubuntu) || "$like" =~ (debian|ubuntu) ]] \
     || command -v apt-get >/dev/null 2>&1; then
    DISTRO_FAMILY="debian"
    PKG_MGR="apt-get"
    PKG_INSTALL="env DEBIAN_FRONTEND=noninteractive apt-get install -y chrony"
    SERVICE="chrony"
    CONF="/etc/chrony/chrony.conf"
  elif [[ "$id" =~ (rhel|centos|fedora|rocky|almalinux) || "$like" =~ (rhel|fedora|centos) ]] \
       || command -v dnf >/dev/null 2>&1 || command -v yum >/dev/null 2>&1; then
    DISTRO_FAMILY="rhel"
    if command -v dnf >/dev/null 2>&1; then
      PKG_MGR="dnf"
      PKG_INSTALL="dnf install -y chrony"
    else
      PKG_MGR="yum"
      PKG_INSTALL="yum install -y chrony"
    fi
    SERVICE="chronyd"
    CONF="/etc/chrony.conf"
  else
    echo "Unsupported distribution (no apt-get/dnf/yum found)." >&2
    return 1
  fi

  # Firewall tool preference: firewalld if running, else ufw if present.
  if command -v firewall-cmd >/dev/null 2>&1; then
    FIREWALL="firewalld"
  elif command -v ufw >/dev/null 2>&1; then
    FIREWALL="ufw"
  else
    FIREWALL="none"
  fi
}

# Build the chrony.conf body into the global CONF_BODY variable.
build_config() {
  if [[ "$MODE" == "manual" ]]; then
    CONF_BODY="$(cat <<EOF
# Generated by ntp-server-setup-multi.sh ($(date +%F_%H%M%S))
# Mode: manual (offline authoritative server)

driftfile /var/lib/chrony/chrony.drift
rtcsync
makestep 1.0 3

# Serve local clock to clients
allow $ALLOW
local stratum 10
EOF
)"
  else
    CONF_BODY="$(cat <<EOF
# Generated by ntp-server-setup-multi.sh ($(date +%F_%H%M%S))
# Mode: online (internet-synced with local fallback)

driftfile /var/lib/chrony/chrony.drift
rtcsync
makestep 1.0 3

# Upstream time source
pool $POOL iburst

# Serve to clients; fall back to local clock only if upstream is unreachable
allow $ALLOW
local stratum 10 orphan
EOF
)"
  fi
}

# run CMD...  -> execute, or just print it in dry-run mode.
run() {
  if [[ "$DRY_RUN" == "yes" ]]; then
    echo "[dry-run] $*"
  else
    eval "$@"
  fi
}

main() {
  detect_distro || exit 1
  build_config

  echo "=== NTP SERVER SETUP (multi-distro) ==="
  echo "Distro family: $DISTRO_FAMILY"
  echo "Package mgr:   $PKG_MGR"
  echo "Service:       $SERVICE"
  echo "Config path:   $CONF"
  echo "Firewall:      $FIREWALL"
  echo "Mode:          $MODE"
  [[ "$MODE" == "online" ]] && echo "Pool:          $POOL"
  [[ "$MODE" == "manual" ]] && echo "Manual time:   $MANUAL_TIME"
  echo "Allow subnet:  $ALLOW"
  [[ -n "$TIMEZONE" ]] && echo "Timezone:      $TIMEZONE"
  echo "Dry run:       $DRY_RUN"
  echo

  echo "----- chrony.conf that would be written to $CONF -----"
  printf '%s\n' "$CONF_BODY"
  echo "------------------------------------------------------"
  echo

  if [[ "$DRY_RUN" == "yes" ]]; then
    echo "[dry-run] Planned actions:"
    echo "[dry-run]   $PKG_MGR update / refresh metadata"
    echo "[dry-run]   $PKG_INSTALL"
    echo "[dry-run]   disable systemd-timesyncd"
    [[ -n "$TIMEZONE" ]] && echo "[dry-run]   timedatectl set-timezone $TIMEZONE"
    [[ "$MODE" == "manual" ]] && echo "[dry-run]   timedatectl set-ntp false && set-time '$MANUAL_TIME'"
    echo "[dry-run]   write config to $CONF (with backup of any existing file)"
    case "$FIREWALL" in
      firewalld) echo "[dry-run]   firewall-cmd --add-service=ntp --permanent && --reload" ;;
      ufw)       echo "[dry-run]   ufw allow 123/udp" ;;
      none)      echo "[dry-run]   (no firewall tool detected; skipping)" ;;
    esac
    echo "[dry-run]   systemctl enable --now $SERVICE"
    echo
    echo "Dry-run complete. No changes were made."
    exit 0
  fi

  # ---- real execution from here ----
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "Run this script as root or with sudo (or use --dry-run)." >&2
    exit 3
  fi

  echo "Installing chrony..."
  if [[ "$PKG_MGR" == "apt-get" ]]; then
    run "apt-get update"
  fi
  run "$PKG_INSTALL"
  run "systemctl disable --now systemd-timesyncd 2>/dev/null || true"

  if [[ -n "$TIMEZONE" ]]; then
    echo "Setting timezone to $TIMEZONE..."
    run "timedatectl set-timezone '$TIMEZONE'"
  fi

  if [[ "$MODE" == "manual" ]]; then
    echo "Setting manual time..."
    run "timedatectl set-ntp false"
    run "timedatectl set-time '$MANUAL_TIME'"
  fi

  # Back up an existing config, then write the new one.
  if [[ -f "$CONF" ]]; then
    run "cp '$CONF' '${CONF}.bak.$(date +%F_%H%M%S)'"
  fi
  echo "Writing $CONF..."
  printf '%s\n' "$CONF_BODY" > "$CONF"

  echo "Configuring firewall ($FIREWALL)..."
  case "$FIREWALL" in
    firewalld)
      run "firewall-cmd --add-service=ntp --permanent >/dev/null 2>&1 || true"
      run "firewall-cmd --reload >/dev/null 2>&1 || true"
      ;;
    ufw)
      run "ufw allow 123/udp >/dev/null 2>&1 || true"
      ;;
    none)
      echo "  No firewall tool detected; skipping."
      ;;
  esac

  echo "Starting $SERVICE..."
  run "systemctl daemon-reload"
  run "systemctl enable '$SERVICE' >/dev/null 2>&1 || true"
  run "systemctl restart '$SERVICE'"

  if ! systemctl is-active --quiet "$SERVICE"; then
    echo "$SERVICE failed to start." >&2
    systemctl status "$SERVICE" --no-pager || true
    exit 1
  fi

  echo
  echo "NTP server ready (mode: $MODE)."
  echo
  chronyc tracking || true
  echo
  chronyc sources -v || true
}

main "$@"
