#!/usr/bin/env bash
set -euo pipefail

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "Run this script as root or with sudo."
    exit 1
  fi
}

valid_ipv4() {
  local ip="$1" IFS=.
  local -a octets
  read -r -a octets <<< "$ip"
  [[ ${#octets[@]} -eq 4 ]] || return 1

  for o in "${octets[@]}"; do
    [[ "$o" =~ ^[0-9]+$ ]] || return 1
    (( o >= 0 && o <= 255 )) || return 1
  done
}

choose_timezone() {
  local query=""
  local -a zones=()
  local choice=""

  while true; do
    echo
    read -rp "Enter a timezone search term (e.g. Europe, Asia, Berlin): " query
    mapfile -t zones < <(timedatectl list-timezones | grep -i -- "${query:-.}" || true)

    if ((${#zones[@]} == 0)); then
      echo "No matching timezones found."
      continue
    fi

    echo
    select choice in "${zones[@]}"; do
      if [[ -n "${choice:-}" ]]; then
        timedatectl set-timezone "$choice"
        echo "Timezone set to: $choice"
        TZ_CHOSEN="$choice"
        return 0
      fi
      echo "Invalid choice."
    done
  done
}

ensure_service_started() {
  if systemctl list-unit-files | grep -q '^chrony\.service'; then
    systemctl enable --now chrony
  elif systemctl list-unit-files | grep -q '^chronyd\.service'; then
    systemctl enable --now chronyd
  else
    echo "chrony service not found."
    exit 1
  fi
}

main() {
  require_root

  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y chrony

  systemctl disable --now systemd-timesyncd 2>/dev/null || true

  choose_timezone

  echo
  while true; do
    read -rp "Enter NTP server IP address: " SERVER_IP
    if valid_ipv4 "$SERVER_IP"; then
      break
    fi
    echo "Invalid IPv4 address."
  done

  local conf="/etc/chrony/chrony.conf"
  local backup="${conf}.bak.$(date +%F_%H%M%S)"
  cp "$conf" "$backup"

  cat > "$conf" <<EOF
# Generated by setup-ntp-client.sh
server $SERVER_IP iburst prefer

driftfile /var/lib/chrony/chrony.drift
rtcsync
makestep 1.0 3
EOF

  ensure_service_started
  systemctl restart chrony 2>/dev/null || systemctl restart chronyd 2>/dev/null || true

  sleep 2
  chronyc -a makestep 2>/dev/null || true

  echo
  echo "Client setup complete."
  echo "Timezone: $(timedatectl show -p Timezone --value)"
  echo "NTP server: $SERVER_IP"
  echo
  chronyc tracking || true
  chronyc sources -v || true
  date
}

main "$@"