#!/usr/bin/env bash
set -euo pipefail

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "Run as root or sudo"
    exit 1
  fi
}

choose_timezone() {
  while true; do
    echo
    read -rp "Search timezone (e.g. Europe, Berlin): " query
    mapfile -t zones < <(timedatectl list-timezones | grep -i -- "${query:-.}" || true)

    if ((${#zones[@]} == 0)); then
      echo "No matches"
      continue
    fi

    echo
    select z in "${zones[@]}"; do
      if [[ -n "${z:-}" ]]; then
        timedatectl set-timezone "$z"
        echo "Timezone set to: $z"
        return
      fi
      echo "Invalid choice"
    done
  done
}

set_manual_time() {
  echo
  echo "Disabling automatic time sync..."
  timedatectl set-ntp false

  read -rp "Enter manual time (YYYY-MM-DD HH:MM:SS): " newtime
  timedatectl set-time "$newtime"

  echo "Time set to: $(date)"
}

install_chrony() {
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y chrony
  systemctl disable --now systemd-timesyncd 2>/dev/null || true
}

configure_chrony() {
  local mode="$1"
  local conf="/etc/chrony/chrony.conf"

  # Back up an existing config only if one is present; on a fresh install the
  # file should exist, but guard so `set -e` does not abort on a missing file.
  if [[ -f "$conf" ]]; then
    cp "$conf" "${conf}.bak.$(date +%F_%H%M%S)"
  fi

  echo "Configuring chrony ($mode mode)..."

  cat > "$conf" <<EOF
# Generated by setup script

driftfile /var/lib/chrony/chrony.drift
rtcsync
makestep 1.0 3

# Allow all clients
allow 0.0.0.0/0
EOF

  if [[ "$mode" == "manual" ]]; then
    # Offline authoritative server: always serve local time at stratum 10.
    echo "local stratum 10" >> "$conf"
  else
    # Internet-synced with a local fallback. The `orphan` option keeps `local`
    # inactive while a real upstream is reachable, so the server only falls
    # back to its own clock when the pool is unreachable.
    cat >> "$conf" <<EOF
pool pool.ntp.org iburst
local stratum 10 orphan
EOF
  fi
}

start_service() {
  systemctl daemon-reload
  systemctl enable chrony
  systemctl restart chrony

  if ! systemctl is-active --quiet chrony; then
    echo "❌ chrony failed"
    systemctl status chrony --no-pager
    exit 1
  fi
}

open_firewall() {
  if command -v ufw >/dev/null 2>&1; then
    ufw allow 123/udp >/dev/null 2>&1 || true
  fi
}

show_status() {
  echo
  echo "==== SERVER STATUS ===="
  chronyc tracking || true
  echo
  chronyc sources -v || true
  echo
  date
}

main() {
  require_root

  echo "=== NTP SERVER SETUP ==="

  install_chrony
  choose_timezone

  echo
  echo "Select mode:"
  echo "1) Manual time (offline authoritative server)"
  echo "2) Internet sync + fallback (recommended)"
  read -rp "Choice [1-2]: " mode_choice

  if [[ "$mode_choice" == "1" ]]; then
    MODE="manual"
    set_manual_time
  else
    MODE="online"
  fi

  configure_chrony "$MODE"
  open_firewall
  start_service

  echo
  echo "✅ NTP Server Ready"
  echo "Mode: $MODE"
  echo "Clients: ALL (0.0.0.0/0)"

  show_status
}

main "$@"